def sum_list(list):
    # pass hade ocksÃ¥ fungerat
    # raise Exception() hade ocksÃ¥ fungerat
    #return None
    return sum(list)